<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>ltv output</name>
  <uuid>7c1c11c4-3565-4538-8c30-cdf23a82023a</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to LTV ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
