<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>surplus out</name>
  <uuid>38adf9a0-5d05-4342-a043-220c7e56fb0d</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to Surplus ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
