<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Max Probability</name>
  <uuid>c426d4da-dd10-4d3d-ae2d-2b9d32d4fc9b</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to the maximum probability of 'ML model invocation' ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
