<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Output Mapping</name>
  <uuid>cf7798af-2eb2-4b8b-aeff-03acc280e2e0</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to a new Mortgage Default Prediction where
		default predicted is Prediction , 
		the probability is Probability ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
