<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>otherwise reject application</name>
  <uuid>25dcebe3-bf97-4636-8e6d-336752726eb5</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to Rejected ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
