<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Get prediction</name>
  <uuid>5dd1870f-f09c-4b8c-b91c-73cce88ba753</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[   set decision to the mortgage default predictor computed from
      applicant being 'Update Applicant Sore' ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
